### ISSUE TITLE
Beaker Notebook not recongizing kernel in OS X

### ISSUE THREAD

**Issue by pgensler** [twosigma/beakerx#4829]
Hi,

I have installed Python 3.5 with Ananconda, but when I try to modify my JSON file as indicated in your help files to point to Ipython, Beaker just seems to hang on the process. Thoughts on what I am doing wrong? Here is my JSON file:

{
  "languages" :{
    "Python3" :{
      "path" : "/Users/petergensler/anaconda/bin/ipython3"
    }
  }
  "autocomplete-parameters" : "true",
  "pref-format" : "1",
  "allow-anonymous-usage-tracking" : false,
  "edit-mode" : "default"
}

Here is what I have installed:Peters-15-MacBook-Pro:~ petergensler$ which ipython3
/Users/petergensler/anaconda/bin/ipython3
Peters-15-MacBook-Pro:~ petergensler$ which ipython2
Peters-15-MacBook-Pro:~ petergensler$ which R
/usr/local/bin/R
Any help would be greatly appreciated. Thanks!

**Comment by scottdraves** [comment]
Are you building Beaker or running it?

In any case, please install Python2 with anaconda and then make a virtual environment for python3, as explained here: http://beakernotebook.com/getting-started

**Comment by pgensler** [comment]
I am just trying to run Beaker, but in order to get Python 3 working, I need to point to it via my JSON file correct? Why would I need to install Python 3 in a virtual environment? The page you referenced does not talk about making a virtual environment for Python 3.

**Comment by scottdraves** [comment]
The `conda create` makes the virtual environment.

> Python3 Installation
> 1. Install Python as above
> 2. Install Python3. Generally you can just say
> conda create -n py3k python=3 anaconda
> 3. Edit your beaker.pref.json file so Beaker knows where to find it.

**Comment by pgensler** [comment]
I already have it installed, as when I run which python3, it gives me the path where it is located.
I think the issue is that my JSON document is not recognizing the file path.

**Comment by scottdraves** [comment]
The JSON files is documented here: https://github.com/twosigma/beaker-notebook/wiki/Language-Preferences

the path attribute should be to the directory that contains the python binary, not to the binary itself.

**Comment by pgensler** [comment]
Ok, so how would I figure out what directory contains my python binary? Isen't that what the which command does, or am I mis understanding something?

**Comment by scottdraves** [comment]
"path" : "/Users/petergensler/anaconda/bin/ipython3"

should be

"path" : "/Users/petergensler/anaconda/bin"

**Comment by pgensler** [comment]
OK, thanks. As I am pretty new to Python, I would strongly recommend that you clarify what the command you run does. I've included a clearer example below:
"
Python3 Installation
1. Install Python as above
2. Install Python3 by creating a virtual environment with the following command:
conda create -n py3k python=3 anaconda
3. Edit your beaker.pref.json file so Beaker knows where to find it.
"

**Comment by scottdraves** [comment]
does it work for you now?

**Comment by pgensler** [comment]
No, it says that it failed to start IPython.

**Comment by scottdraves** [comment]
OK but you are trying to run Python3, right?

**Comment by pgensler** [comment]
Correct

**Comment by scottdraves** [comment]
Then, when you create a notebook and open the language manager, click on "Python3" not "IPython".

**Comment by pgensler** [comment]
So I tried to run Python3 and IPython, but it still fails, and both are just pending to complete. Thoughts?

**Comment by pgensler** [comment]
This is my json file now with the updates:

> {
>   "languages" :{
>     "IPython" :{
>       "path" : "/Users/petergensler/anaconda/bin"
>     },
>     "Python3" :{
>       "path" : "/Users/petergensler/anaconda/bin"
>     }
>   }
>   "pref-format" : "1",
>   "allow-anonymous-usage-tracking" : false,
>   "edit-mode" : "default"
> }

**Comment by scottdraves** [comment]
You should remove the IPython section since you don't have Python2.
Create an empty notebook, and add just Python3.

**Comment by pgensler** [comment]
I wonder if it has something to do with this error about R below:
I do have R installed on my machine, but not in the json document.
![2016-10-18_17-10-46](https://cloud.githubusercontent.com/assets/7308115/19498326/da7ed2ba-9555-11e6-8d1c-4480f22cba33.png)

**Comment by scottdraves** [comment]
No, I can debug that too but I would rather do them one at a time.

**Comment by pgensler** [comment]
Let me know what you need from my end to help with the debugging.

**Comment by scottdraves** [comment]
If you are looking for a hassle-free way of running Beaker including all the languages, I recommend https://github.com/twosigma/beaker-notebook/wiki/Running-the-Docker-Container

to debug Python3:
1) remove IPython from your json config file
2) restart beaker
3) create an empty notebook
4) open the language manager
5) click on "Python3"

**Comment by pgensler** [comment]
I just did those steps, and I get the message: 
![2016-10-18_17-32-03](https://cloud.githubusercontent.com/assets/7308115/19498855/ce3e0b08-9558-11e6-8d83-a9e2086d1389.png)

**Comment by scottdraves** [comment]
does the "Initializing Python3" spinner go away?  it should either finish or give an error.

**Comment by pgensler** [comment]
Both give an error saying that they both failed to initialize.

**Comment by pgensler** [comment]
I think I installed Python 3 with Anaconda, so do you think I need to uninstall it and install it differently, and into a VM?

**Comment by scottdraves** [comment]
The Docker container is definitely the most reliable way to get it working.

Python3 requires Python2 and it doesn't look like you have it so I am not surprised it doesn't work.

**Comment by pgensler** [comment]
I have python2 installed (its part of OS X)
Peters-15-MacBook-Pro:~ petergensler$ which python2
/Library/Frameworks/Python.framework/Versions/2.7/bin/python2

**Comment by scottdraves** [comment]
That's not the same as installing with anaconda.

**Comment by pgensler** [comment]
I see, I'll have to install with anaconda, and get back to you on if it works or not. Dident know I needed Python 2 for Python 3.

**Comment by scottdraves** [comment]
You will have to delete the Python3 you have and start over....

**Comment by pgensler** [comment]
So after doing some research today, I found out that Python 3 DOES NOT require Python 2. Furthermore, I tried creating a new virtual machine with Python 3, and modified my JSON file as requested, but it still fails to load. I even tried setting up beaker with my python3 from anaconda (like this), and it still failed, which leads me to believe that this is definitely a bug.
/Users/petergensler/anaconda/bin/python3

Do you think it has something to do with the packages I have installed, that could be interfering?

**Comment by scottdraves** [comment]
Python3 in general does not, but the way Beaker runs it, it does.
Also yes it does require a handful of packages to be installed, but they are in the default set so that is not likely a factor.

Mostly I recommend you avoid all this hassle by using the docker container (see above).

**Comment by pgensler** [comment]
Yeah I am having issues with the docker container as well...I try to connect to it with the IP it gives me, but it says the server can't be reached, and the DNS can not be found. 
This is my output:

> petergensler$ eval "$(docker-machine env default)"
> Peters-15-MacBook-Pro:~ petergensler$ docker run -p 8800:8800 -t beakernotebook/beaker
> 
> starting nginx instance (/home/beaker/src/core/nginx)
> nginx-stderr>nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
> [main] INFO org.eclipse.jetty.server.Server - jetty-8.1.13.v20130916
> [main] INFO org.eclipse.jetty.server.AbstractConnector - Started SelectChannelConnector@127.0.0.1:8802
> 
> Connecting to https://79f3164c393b:8800/
> Submit this password: qvpi5rr5p5lr7jrcb8ik

**Comment by scottdraves** [comment]
please follow the instructions in the wiki for running the container.

**Comment by pgensler** [comment]
OK, I did that, but when I go to the IP address listed, I get this:
This site can’t be reached

127.0.0.1 refused to connect.

**Comment by scottdraves** [comment]
did you use the right port?  it's not 8800 anymore....

**Comment by pgensler** [comment]
Yeah I'm using 8801, not 8800

**Comment by pgensler** [comment]
This is what I'm running:

>  petergensler$ eval "$(docker-machine env default)"
> Peters-15-MacBook-Pro:~ petergensler$ docker run -v $HOME:/home/beaker/host -p 127.0.0.1:8801:8801 -t beakernotebook/beaker-prerelease su -m beaker -c 'export PATH=$PATH:/usr/sbin && /home/beaker/src/core/beaker.command --connect-host 127.0.0.1 --listen-interface *'
> 
> [main] INFO com.twosigma.beaker.core.rest.PluginServiceLocatorRest - starting nginx instance (/home/beaker/src/core/nginx)
> [Thread-4] INFO com.twosigma.beaker.core.rest.StreamGobbler - nginx-stderr>nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
> [main] INFO org.eclipse.jetty.server.Server - jetty-8.1.13.v20130916
> [main] INFO com.twosigma.beaker.core.module.elfinder.impl.DefaultFsService - mounted A: LocalFsVolume [/home/beaker]
> [main] INFO com.twosigma.beaker.core.module.elfinder.impl.DefaultFsService - mounted B: LocalFsVolume [/]
> [main] INFO org.eclipse.jetty.server.AbstractConnector - Started SelectChannelConnector@127.0.0.1:8802

Connecting to http://127.0.0.1:8801/

When I go to that IP, it just says that 127.0.0.1 refused to connect. I started and stopped the container to ensure a fresh, new one as well.

**Comment by scottdraves** [comment]
what does it print out as it starts?

BeakerNotebook.com
ScottDraves.com
twitter.com/Scott_Draves

**Comment by scottdraves** [comment]
i think you are missing the / before the \* in the listen argument

**Comment by pgensler** [comment]
Ok, I fixed the /, and I'm still getting the same error, where it refuses to connect. Thoughts?

**Comment by scottdraves** [comment]
please show the complete log of you running the container and what it outputs

**Comment by pgensler** [comment]
Sure, here is my script:
The Listen argument does have a backslash \, but I don't know why it wont keep it like that when I post it.

Peters-15-MacBook-Pro:~ petergensler$ eval "$(docker-machine env default)"
Peters-15-MacBook-Pro:~ petergensler$ docker run -v $HOME:/home/beaker/host -p 127.0.0.1:8801:8801 -t beakernotebook/beaker-prerelease su -m beaker -c 'export PATH=$PATH:/usr/sbin && /home/beaker/src/core/beaker.command --connect-host 127.0.0.1 --listen-interface \ *'
[main] INFO com.twosigma.beaker.core.rest.PluginServiceLocatorRest - starting nginx instance (/home/beaker/src/core/nginx)
[Thread-4] INFO com.twosigma.beaker.core.rest.StreamGobbler - nginx-stderr>nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
[main] INFO org.eclipse.jetty.server.Server - jetty-8.1.13.v20130916
[main] INFO com.twosigma.beaker.core.module.elfinder.impl.DefaultFsService - mounted A: LocalFsVolume [/home/beaker]
[main] INFO com.twosigma.beaker.core.module.elfinder.impl.DefaultFsService - mounted B: LocalFsVolume [/]
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started SelectChannelConnector@127.0.0.1:8802

Connecting to http://127.0.0.1:8801/

**Comment by scottdraves** [comment]
idk doesn't make sense, sorry

**Comment by pgensler** [comment]
I think the line above is what is causing my container to fail.

> [Thread-4] INFO com.twosigma.beaker.core.rest.StreamGobbler - nginx-stderr>nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)

**Comment by scottdraves** [comment]
no that's normal.  here it is working on my mac, including that line which is just a quirk of nginx:

```
$ docker run -v $HOME:/home/beaker/host -p 127.0.0.1:8801:8801 -t beakernotebook/beaker-prerelease su -m beaker -c 'export PATH=$PATH:/usr/sbin && /home/beaker/src/core/beaker.command --connect-host 127.0.0.1 --listen-interface \*'
[main] INFO com.twosigma.beaker.core.rest.PluginServiceLocatorRest - starting nginx instance (/home/beaker/src/core/nginx)
[main] INFO org.eclipse.jetty.server.Server - jetty-8.1.13.v20130916
[Thread-19] INFO com.twosigma.beaker.core.rest.StreamGobbler - nginx-stderr>nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
[main] INFO com.twosigma.beaker.core.module.elfinder.impl.DefaultFsService - mounted A: LocalFsVolume [/home/beaker]
[main] INFO com.twosigma.beaker.core.module.elfinder.impl.DefaultFsService - mounted B: LocalFsVolume [/]
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started SelectChannelConnector@127.0.0.1:8802

Connecting to http://127.0.0.1:8801/
```

**Comment by scottdraves** [comment]
i think this should be fixed by 1.7, just released.

**Comment by pgensler** [comment]
Hmm, I'm getting this error message now.....
petergensler$ docker run -v $HOME:/home/beaker/host -p 127.0.0.1:8801:8801 -t beakernotebook/beaker su -m beaker -c 'export PATH=$PATH:/usr/sbin && /home/beaker/src/core/beaker.command --connect-host 127.0.0.1 --listen-interface *'
Exception in thread "main" org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: --connect-host
    at org.apache.commons.cli.Parser.processOption(Parser.java:363)
    at org.apache.commons.cli.Parser.parse(Parser.java:199)
    at org.apache.commons.cli.Parser.parse(Parser.java:85)
    at com.twosigma.beaker.core.Main.parseCommandLine(Main.java:103)
    at com.twosigma.beaker.core.Main.main(Main.java:167)

**Comment by scottdraves** [comment]
i meant the previous attempt, before you tried docker.

but if you want to try docker, you need to "pull" to get the most recent version.

**Comment by pgensler** [comment]
Hmm I re pulled the latest image from DockerHub, and I still get the following error:

> [Thread-4] INFO com.twosigma.beaker.core.rest.StreamGobbler - nginx-stderr>nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)

Should I be running the container with sudo as a admin?

**Comment by scottdraves** [comment]
that's normal, should still work

BeakerNotebook.com
ScottDraves.com
twitter.com/Scott_Draves

**Comment by pgensler** [comment]
When I try to run the container as specified, I get the following error:

```
docker run -v $HOME:/home/beaker/host -p 127.0.0.1:8801:8801 -t beakernotebook/beaker su -m beaker -c 'export PATH=$PATH:/usr/sbin && /home/beaker/src/core/beaker.command --connect-host 127.0.0.1 --listen-interface \*'
docker: Cannot connect to the Docker daemon. Is the docker daemon running on this host?.
```

I've tried re running the container in docker quickstart, and I get the same message. Thoughts?

**Comment by scottdraves** [comment]
you need to start docker or something.

BeakerNotebook.com
ScottDraves.com
twitter.com/Scott_Draves

**Comment by pgensler** [comment]
Ok, I got the container to run with the following bash command:

`docker run -v $HOME:/home/beaker/host -p 8801:8801 -t beakernotebook/beaker su -m beaker -c "export PATH=$PATH:/usr/sbin && /home/beaker/src/core/beaker.command --listen-interface '*'"
`
I'll send over a pull request in the next day or so to try and revamp the instructions for the container, as it was a bit hard to launch, and get up and running.

I'd strongly recommend that you set up a gitter channel for help for other users so that someone like me has a platform for help, rather than bloating the bug log in github.

**Comment by scottdraves** [comment]
it looks like you omitted the "127.0.0.1:" from the port mapping, which makes your computer open to attack from anyone on your LAN.  if you need to do that you should use the password protected version.

We don't have the staff resources to run a chat room, sorry.  That would also give the false impression that we can respond interactively.

**Comment by palbarede** [comment]
Hello,
Mac OS X 10.11.6, trying to use  ipython 6.1.0 or python 3.5.3 installed in /Applications/anaconda/bin, Beaker 1.7.1 does not launch.

Config file:

{
  "autocomplete-parameters" : "true",
  "pref-format" : "1",
  "edit-mode" : "default"
}


{
  "languages" : {
    "Python3" : {
      "path" : "/Applications/anaconda/bin"
    }
  },
  "pref-format" : "1",
  "advanced-mode" : false,
  "allow-anonymous-usage-tracking" : true
}

System log :

2017/6/15 19:25:58,582 Beaker[603]: com.google.inject.ProvisionException: Guice provision errors:

1) Error injecting constructor, java.lang.NullPointerException
  at com.twosigma.beaker.core.module.config.DefaultBeakerConfig.<init>(DefaultBeakerConfig.java:100)
  at com.twosigma.beaker.core.module.config.DefaultBeakerConfig.class(DefaultBeakerConfig.java:100)
  while locating com.twosigma.beaker.core.module.config.DefaultBeakerConfig
  while locating com.twosigma.beaker.core.module.config.BeakerConfig
    for parameter 0 at com.twosigma.beaker.core.rest.PluginServiceLocatorRest.<init>(PluginServiceLocatorRest.java:70)
  at com.twosigma.beaker.core.module.URLConfigModule.configureServlets(URLConfigModule.java:92)
  while locating com.twosigma.beaker.core.rest.PluginServiceLocatorRest

1 error


With the default config file, beaker would launch.

As far as I understand, the proposed solution was to reinstall all languages in docker container but I do not like it.

Has the situation evolved ?
