### ISSUE TITLE
python kernel demos under doc/contents not working in binder

### ISSUE THREAD

**Issue by Analect** [twosigma/beakerx#6325]
Thanks for your work on beakerx.

I was curious to see beakerx running, so opted for the short-cut route via the binder button on your README.  It could be that these demos are a WIP, but just thought I'd mention that for some reason I was **not** able to get most of the python-based notebooks (e.g. `categoryPlot_python.ipynb`) to output visualisations/charts by performing a `Run All` cells, whereas most of the notebooks with a groovy kernel did work.  The only python one that did appear to work was `OutputContainersAndLayoutManagers_python.ipynb`.

I was interested to see your `tablesawDemo.ipynb` using quandl data, although that is somehow broken currently.

```
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
script15107884950032073587986.groovy: 2: unable to resolve class Table 
 @ line 2, column 7.
   Table table = session.getDataSet(DataSetRequest.Builder.of("WIKI/AAPL").build());
         ^

script15107884950032073587986.groovy: 4: unable to resolve class ShortColumn 
 @ line 4, column 13.
   ShortColumn yearColumn = table.dateColumn("Date").year();
```

**Comment by scottdraves** [comment]
Hi, thanks for the report.  We just enabled Binder today and it hasn't been tested much.
The demos work great in a normal BeakerX install, but indeed something is funky on Binder.
I got the following error from most of the Python plotting demos:
```
/user/twosigma-beakerx-fotpc45f/nbextensions/beakerx/index.js?v=20171116000328:83 Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at /user/twosigma-beakerx-fotpc45f/nbextensions/beakerx/index.js?v=20171116000328:83
    at Array.map (<anonymous>)
    at child.getNumberOfPointsForStandardPlot (/user/twosigma-beakerx-fotpc45f/nbextensions/beakerx/index.js?v=20171116000328:83)
    at child.limitPoints (/user/twosigma-beakerx-fotpc45f/nbextensions/beakerx/index.js?v=20171116000328:83)
    at /user/twosigma-beakerx-fotpc45f/nbextensions/beakerx/index.js?v=20171116000328:83
    at <anonymous>
```
The time series plotting and interactive tables worked fine however.

I got that same JS plot error from one of the plots in the tablesaw demo, which leads me to think there is some race condition in the JS  and it's not Python specific.

But the error you are seeing sounds like you just went right to the quandl cells without starting at the top of the notebook.  The first cell loads tablesaw into the classpath and imports it.
If I skip that I get the same error as you report, but If I run the 1st cell, it works.

Note that Tablesaw has built a BeakerX connector so that our demo will improve:
https://github.com/jtablesaw/tablesaw/issues/190
Right now the tables are showing up in ascii instead of using our table widget.
You can manually include the connector like our other tablesaw demo, or when tablesaw releases theirs, it should just work.

**Comment by Analect** [comment]
@scottdraves 
Thanks for the info.
I tried building my own image following the [release docs](https://github.com/twosigma/beakerx/blob/master/RELEASE.md#release-to-docker-hub), as the version of beakerx on dockerhub isn't the latest 0.8.  However, it stumbled at the last part, complaining about there being no `beakerx-install` command.  Maybe that [setup.sh](https://github.com/twosigma/beakerx/blob/master/docker/setup.sh) files needs tweaking, as that final `RUN /home/beakerx/setup.sh` command is what is failing, as per logs below.

https://gist.github.com/Analect/8ca793e9b5b05e8155226d1078c01ea5

**Comment by scottdraves** [comment]
0.8.1 should be on docker hub now, please LMK how it works for you.

**Comment by Analect** [comment]
@scottdraves  ... thanks for updating the docker hub.
I'm keen to get things working in a jupyterhub context and also have jupyterlab loaded (in the knowledge that much of the beakerx stuff is not necessarily ready to work on there yet).  There are a few other python packages I need to load for my own custom `jupyter_notebook_config.py` too.  I note from the the `beakerx/beakerx:latest` image that hub/lab packages aren't installed ... and so I'm keen to try to build the images myself ... rather than just trying to pin on these extra installs using a `FROM  beakerx/beakerx:latest`.

```
beakerx@ca83c1470315:~$ conda list | grep jupyter
jupyter                   1.0.0            py36h9896ce5_0
jupyter_client            5.1.0            py36h614e9ea_0
jupyter_console           5.2.0            py36he59e554_1
jupyter_core              4.3.0            py36h357a921_0
```
As per the [thread above](https://github.com/twosigma/beakerx/issues/6325#issuecomment-344911152), I was having some difficulties in building the second of these images below (i.e 
 the one that supplies the docker hub registry). Is this something you/others are seeing?  Can you suggest a work-around?

```
docker build -t beakerx-base -f docker/base/Dockerfile .
docker build -t beakerx -f docker/Dockerfile .
```
Also, I notice these beakerx images are beginning to become rather chunky in size.  Do you know what might be causing this circa growth of 1GB in the latest version?

```
REPOSITORY                TAG                 IMAGE ID            CREATED             SIZE
beakerx/beakerx           latest              50b2bc01ec74        2 hours ago         5.14 GB  (ver 0.8.1)
beakerx/beakerx           latest              f07643c031e1        2 weeks ago         4.269 GB (ver 0.7.0)
```
Thanks.

**Comment by MariuszJurowicz** [comment]
@scottdraves
The js error complaining about the `Array.map` should be fixed in https://github.com/twosigma/beakerx/pull/6338. But somehow the binder build is not using the latest version.

**Comment by scottdraves** [comment]
binder uses the released version from conda forge, so this fix should appear with 0.9.0

**Comment by scottdraves** [comment]
the docker build on master should be good as of https://github.com/twosigma/beakerx/commit/c333d40da695d236456b1da53bf918cabe247d12
are you still getting an error?

**Comment by Analect** [comment]
@scottdraves  ... yes, I'm still getting an error when trying to build these images.

I'm working from this latest master commit [731810a](https://github.com/twosigma/beakerx/commit/731810a826fed5995e1b56cf122cfb0622996a4b), which post-dates your suggested fix commit above, so presumably should work.

As per the logs [here](https://gist.github.com/Analect/f8470a6ef742cd347efc14f490ced8c5#file-logs-beakerx-image-txt), there appears to be still a problem with a missing `beakerx-install` command on step 15 of the main Dockerfile (as opposed to the base one).  I haven't modified either of the dockerfiles other than to change the base image to what I have built locally using the `docker/base/Dockerfile`.

I think you mention above that binder is using a conda-forge version of beakerx-feedstock, as defined in the `environment.yaml` file.  Given that I'm looking to run beakerx on jupyterhub, akin to binder, can I confirm if this conda-forge version of beakerx comes pre-loaded with both jupyterhub and jupyterlab?  Thanks.

**Comment by scottdraves** [comment]
Python plots working in Binder now.

And we have made several improvements to the docker image, and it's size is down by 400MB.
It should build fine please LMK if that is not the case.
We haven't preloaded jupyterhub and jupyterlab.
Now that we support lab that one makes sense to add.
I don't use jupyterhub myself, is it a simple "conda install -c conda-forge jupyterhub"?

**Comment by scottdraves** [comment]
so i think this issue is closed.  will track the remaining docker work with https://github.com/twosigma/beakerx/issues/6429

**Comment by scottdraves** [comment]
https://github.com/twosigma/beakerx/pull/6472 adds jupyter lab.

not sure what you mean about supporting hub...
