### ISSUE TITLE
Future Warning in Table  Display

### ISSUE THREAD

**Issue by JohnOmernik** [twosigma/beakerx#8097]
Getting this when tables are displayed. Only started happening recently.

/opt/conda/lib/python3.7/site-packages/beakerx/tabledisplay/tabledisplay.py:109: FutureWarning: The 'get_values' method is deprecated and will be removed in a future version. Use '.to_numpy()' or '.array' instead.
  value = args[0][columnName].get_values()[index]

**Comment by jaroslawmalekcodete** [comment]
Hi @JohnOmernik 
I'm not able to reproduce this warning.
Could you provide more details?

**Comment by JohnOmernik** [comment]
So I just did a bunch of upgrading. Running BeakerX 1.4.0, and recent versions of Pandas and Jupyter Lab and still getting:

/opt/conda/lib/python3.7/site-packages/beakerx/tabledisplay/tabledisplay.py:109: FutureWarning: The 'get_values' method is deprecated and will be removed in a future version. Use '.to_numpy()' or '.array' instead.
  value = args[0][columnName].get_values()[index]
/opt/conda/lib/python3.7/site-packages/beakerx/tabledisplay/tabledisplay.py:114: FutureWarning: The 'get_values' method is deprecated and will be removed in a future version. Use '.to_numpy()' or '.array' instead.
  index_values = args[0].index.get_values()[index]

**Comment by piorek** [comment]
@jaroslawmalekcodete I saw these warnings and fixed them while extracting table display so it's fixed in the current master, but i don't think it's released yet

**Comment by JohnOmernik** [comment]
What is the timeline for 1.4.1 to be released (into the Conda repos?)

**Comment by mahsheed** [comment]
With Beakerx version 1.4.1, I am getting the same warning:
```
/opt/conda/lib/python3.7/site-packages/beakerx/tabledisplay/tabledisplay.py:109: FutureWarning: The 'get_values' method is deprecated and will be removed in a future version. Use '.to_numpy()' or '.array' instead.
  value = args[0][columnName].get_values()[index]
```

**Comment by JohnOmernik** [comment]
Yes, and when Pandas got updated to 1.0.0 the get_values is gone, and is now erroring out instead of just providing warnings.

**Comment by mahsheed** [comment]
Originally, I got this warning and error mentioned above from following the JupyterLab installation instructions provided from the BeakerX [website](http://beakerx.com/documentation), but installing in the following way instead seems to prevent the error. However, I still get the warning "tabledisplay.py:109: FutureWarning: The 'get_values' method is deprecated and will be removed in a future version. Use '.to_numpy()' or '.array' instead."

```
pip install beakerx==1.4.1
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install beakerx-jupyterlab
pip install py4j
beakerx install
```

**Comment by SichongP** [comment]
Is there a timeline to release a fix to conda repo? Now it errors out instead of giving warnings with pandas at 1.0.0:
```
AttributeError: 'Series' object has no attribute 'get_values'
```

I have following packages:
\- beakerx=1.4.1=py37_1
\- pandas=1.0.0=py37h0573a6f_0
\- numpy=1.18.1=py37h4f9e942_0
\- jupyterlab=1.2.6=py_0

**Comment by JohnOmernik** [comment]
This has to do with an issue between beakerx and Pandas 1.0, hence why we
were getting future warnings on the version of Pandas just prior to 1.0, it
was warning us something was going away, now that Pandas is 1.0, this is
not working.

**Comment by SichongP** [comment]
Yes I got that the issue was caused by a deprecated function call in beakerx. I was wondering when it will be updated to be compatible with latest pandas?

Right now I can make it work by downgrading pandas but at some point people will surely need later versions of pandas.

This seems to have been fixed in the master branch but not in conda repo?
